// components/Footer.vue
<script setup lang="ts">
import { siteData } from '@/siteData';
</script>

<template>
<footer class="bg-gradient-to-r from-[#000000] to-[#252525] text-center py-4 mt-4 text-white font-normal">
    <a class="text-2xl hover:text-[#feb201] flex justify-center gap-2 text-center" :href="siteData.socials.instagram" target="_blank"><Icon name="mdi:instagram" size="30px" /><span>Siga no Instagram</span></a>
  
  <p class="mt-2">Copyright © 2025 - <span class="ml-auto">Desenvolvido por <a href="https://lzart.com.br" target="_blank" class="underline">LZArt</a></span></p>
</footer>
</template>

// src/app/components/footer/footer.component.ts
import { Component, input } from '@angular/core';
import { SiteData } from '../../../types';

@Component({
  selector: 'app-footer',
  imports: [],
  template: `
    <footer
      class="bg-gradient-to-r from-[#000000] to-[#252525] text-center py-4 mt-4 text-white font-normal"
    >
      <a
        class="text-2xl hover:text-[#feb201] flex justify-center gap-2 text-center"
        [href]="siteData().socials.instagram"
        target="_blank"
        ><span>IGICON Siga no Instagram</span></a
      >

      <p class="mt-2">
        Copyright © 2025 -
        <span class="ml-auto"
          >Desenvolvido por
          <a href="https://lzart.com.br" target="_blank" class="underline"
            >LZArt</a
          ></span
        >
      </p>
    </footer>
  `,
})
export class FooterComponent {
  siteData = input.required<SiteData>();
}
