// src/app/components/gallery/gallery.component.ts
import { Location } from '@angular/common';
import { Component, effect, signal } from '@angular/core';
import { Title } from '@angular/platform-browser';
import { ActivatedRoute } from '@angular/router';
import { ImageLooperComponent } from '../image-looper/image-looper.component';
import { QueryComponent } from '../query/query.component';
import { VideoLooperComponent } from '../video-looper/video-looper.component';

@Component({
  selector: 'app-gallery',
  imports: [ImageLooperComponent, QueryComponent, VideoLooperComponent],
  template: `
    <div>
      <app-query [(searchModel)]="category" />
      <nav class="flex flex-row justify-center items-center pt-4 gap-4">
        <button
          (click)="scrollIntoView('imageProjects')"
          class="text-xl px-5 py-2 bg-[#feb201] hover:bg-[#d79600] active:scale-95 rounded uppercase text-white font-bold shadow-md cursor-pointer"
        >
          Fotos
        </button>
        <button
          (click)="scrollIntoView('videoProjects')"
          class="text-xl px-5 py-2 bg-[#feb201] hover:bg-[#d79600] active:scale-95 rounded uppercase text-white font-bold shadow-md cursor-pointer"
        >
          Videos
        </button>
      </nav>
      <app-image-looper #images [category]="category()" />
      <app-video-looper #videos [category]="category()" />
    </div>
  `,
})
export class GalleryComponent {
  category = signal('Todos');
  constructor(
    private route: ActivatedRoute,
    private location: Location,
    private title: Title
  ) {
    this.title.setTitle('Galería - NG Maker');
    this.route.params.subscribe((params) => {
      if (params['category']) {
        this.category.set(params['category']);
      } else {
        this.category.set('Todos');
      }
    });
    effect(() => {
      this.location.replaceState(`gallery/${this.category()}`);
    });
  }
  scrollIntoView(id: string) {
    let element = document.getElementById(id);
    if (element) {
      element.scrollIntoView({ behavior: 'smooth' });
    }
  }
}

// pages/gallery.vue
<script setup lang="ts">
import { ref } from 'vue';

useHead({
  title: 'Galeria',
})

const props = defineProps({
  category: {
    type: String,
    default: 'todos'
  }})
  
const searchRef = ref(props.category)
  
type MediaLooperRef = {
  rootEl: HTMLElement | null
}

const imagesRef = ref<MediaLooperRef | null>(null)
const videosRef = ref<MediaLooperRef | null>(null)


const scrollIntoView = (section: 'images' | 'videos') => {
  const targetRef = section === 'images' ? imagesRef : videosRef
  if (!targetRef.value?.rootEl) return
  targetRef.value.rootEl.scrollIntoView({ behavior: 'smooth' })
}

</script>
<template>
<div>
  <Query v-model="searchRef"/>
  <nav class="flex flex-row justify-center items-center pt-4 gap-4">
    <button @click="scrollIntoView('images')" class="text-xl px-5 py-2 bg-[#feb201] hover:bg-[#d79600] rounded uppercase text-white font-bold shadow-md">Fotos</button>
    <button @click="scrollIntoView('videos')" class="text-xl px-5 py-2 bg-[#feb201] hover:bg-[#d79600] rounded uppercase text-white font-bold shadow-md">Videos</button>
  </nav>
  <ImageLooper ref="imagesRef" :show-button="false" :limit-posts="false" :filter="searchRef"/>
  <VideoLooper ref="videosRef" :show-button="false" :limit-posts="false" :filter="searchRef"/>
</div>
</template>
