// components/Query.vue
<script lang="ts" setup>
import { siteData } from '@/siteData';

const searchModel = defineModel({ default: 'todos'})

const categories = computed(() => {
  const allItems = [...siteData.projects.images, ...siteData.projects.videos]
  const allTags = allItems.flatMap(item => 
    item.tag
      .split(' ')  // Split by space to handle multiple tags
      .filter(tag => tag.trim()) // Remove empty strings
      .map(tag => tag.replace('#', '')) // Remove '#' symbol
  )
  const uniqueTags = [...new Set(allTags)] // Remove duplicates
  return uniqueTags.sort((a, b) => a.localeCompare(b))
})

</script>
<template>
  <search class="flex flex-col justify-center items-center pt-4">
    <p>Filtrar por:</p>
    <select v-model="searchModel" class="dark:bg-stone-700 dark:text-inherit">
        <option value="todos">Todos</option>
        <option v-for="tag in categories" :key="tag" :value="tag">
          {{ tag }}
        </option>
      </select>
  </search>
</template>

// src/app/components/query/query.component.ts
import { Component, computed, model, NO_ERRORS_SCHEMA } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { siteData } from '../../../siteData';

@Component({
  selector: 'app-query',
  imports: [FormsModule],
  schemas: [NO_ERRORS_SCHEMA],
  template: `
    <search class="flex flex-col justify-center items-center pt-4">
      <p>Filtrar por:</p>
      <select
        [(ngModel)]="searchModel"
        class="dark:bg-stone-700 dark:text-inherit"
      >
        <option value="Todos">Todos</option>
        @for (option of options(); track option) {
        <option [value]="option">
          {{ option }}
        </option>
        }
      </select>
    </search>
  `,
})
export class QueryComponent {
  searchModel = model('todos');
  options = computed(() => {
    const allItems = [...siteData.projects.images, ...siteData.projects.videos];
    const allTags = allItems.flatMap(
      (item) =>
        item.tag
          .split(' ') // Split by space to handle multiple tags
          .filter((tag) => tag.trim()) // Remove empty strings
          .map((tag) => tag.replace('#', '')) // Remove '#' symbol
    );
    const uniqueTags = [...new Set(allTags)]; // Remove duplicates
    return uniqueTags.sort((a, b) => a.localeCompare(b));
  });
}
